# 服务配置
server:
  port: 80

# 启用Swagger文档
swagger.enable: true
# 启用全局方法日志
appMethodLogger.enable: true

# Https配置
sslserver:
  port: 443
  keyStore: .keystore
  keyStorePassword: changeit
  keyStoreType: JKS

# Spring配置
spring:
  http:
    multipart: #文件上传大小限制
      maxFileSize: 1024MB
      maxRequestSize: 10240MB
  jackson: # Jackson配置
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
  datasource: # 数据库配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service?useUnicode=true
    username: service
    password: service

# Security配置
security:
  ignored:
    - assets/**
    - vendor/**
    - favicon.ico
    - login.html
